### ISSUE TITLE
rate-limiting for the API

### ISSUE THREAD

**Issue by jacekkopecky** [jacekkopecky/living-meta-analysis#4]
there is no rate-limiting for the API, which may translate into an issue with google storage quotas

**Comment by Jnnybrrn** [comment]
Reading a little into this, found some interesting links.

An [open issue](https://code.google.com/p/googleappengine/issues/detail?id=6733) asking for a google style over-arching solution to this... And the response is non existent.

We will be able to set usage quota's to prevent the billing going thru the roof, but that will have the problem of - Get DoS'd everyone else for the <time period> gets a 500 - out of quota.

So the DoS succeeds, we just are not billed something rotten for it.

Google provide some means of[ DoS prevention](https://cloud.google.com/appengine/docs/python/config/dos) but it seems up to 1000 IP's may be blacklisted... Not the most helpful?  Furthermore, unless I'm blind there doesn't even seem to be a nodejs version of this functionality, so we might not even be able to use it.

I found an [article](http://blog.simonwillison.net/post/57956846132/ratelimitcache) which talks about how to use another google service (memcache, w/ its free quota's) to keep a counter on how many requests per IP and then build the pages to simply deny the request if this exceeds some limit.. In other words, roll our own rate-limiting.

This is unfortunate, maybe there is a nodejs framework that's r2g for this purpose. Will continue to dig.

**Comment by jacekkopecky** [comment]
Good finds, thanks!

**Comment by jacekkopecky** [comment]
closed in favour of goo.gl/msJ8nE ... erm trello
