### ISSUE TITLE
UI: link should be width-limited

### ISSUE THREAD

**Issue by jacekkopecky** [jacekkopecky/living-meta-analysis#6]
probably see http://jacekkopecky.g.port.ac.uk:8088/jackopecky@gmail.com/Be94/ with whatever your email address ends up being

the "link" field needs to be width-limited, with ellipsis

test it with and without editing

**Comment by Jnnybrrn** [comment]
On working on this, I toyed with the idea of having a :hover event for the non-editable user facing links.

Something like...

```
#paper .link .notediting:hover {
  white-space: pre-line;
  overflow: visible;
  text-overflow: unset;
  word-wrap: break-word;
}
```

It works OK, and for someone who likes to judge a link before they click it, it works well. However its likely unnecessary fluff.

I'm going to leave it out of solving this issue and if needed it can be added in later.

**Comment by Jnnybrrn** [comment]
Pull Request #9 

Raises a question; What does a typical DOI look like? Do we need a similar approach with them?

**Comment by jacekkopecky** [comment]
DOIs are relatively short (though unconstrained); the longest I found in the DOI handbook is `doi:10.1006/jmbi.1998.2354`

but that brought up #10
