### ISSUE TITLE
show charts when all experiments are excluded or when there's no data

### ISSUE THREAD

**Issue by jacekkopecky** [jacekkopecky/living-meta-analysis#66]
forest plot and grape chart should be showing, but empty, when all experiments are excluded and when there's simply no data

**Comment by rragoomundun** [comment]
One part of the work is done here, I need to find out how to display graph without any paper.

![graph-plot](https://cloud.githubusercontent.com/assets/15065784/25179614/96759fa8-2502-11e7-97f3-186b03a67437.png)
![grape-chart](https://cloud.githubusercontent.com/assets/15065784/25179613/96756bd2-2502-11e7-89e4-8f2e3eb3933b.png)

**Comment by jacekkopecky** [comment]
closed in #68, thank you
