### ISSUE TITLE
Visiting someone else's profile - formatting

### ISSUE THREAD

**Issue by Jnnybrrn** [jacekkopecky/living-meta-analysis#8]
When visiting a users profile (who isn't yourself / you're not logged in) the formatting for the table title for  "<Persons name> meta-analyses" falls over if the users Forenames longer than x..

I would recommend we instead just remove the name from here. Its clear from the "Personal info" section (which has the name in full) whose profile we're on and simply "Meta-analyses" and "Papers" would probably work?

I've attached a screen grab.
![lima screengrab](https://cloud.githubusercontent.com/assets/9538578/19114711/0f62fb0e-8b07-11e6-8b19-61af039f4a04.png)

**Comment by jacekkopecky** [comment]
current thinking: simply remove the name when the user isn't you, but keep "your" on a page that isn't about you (your public-facing profile); see GitHub's use of "your" on the homepage https://github.com/ when logged in.
