### ISSUE TITLE
Access to gcloud saved data is still possible after log out

### ISSUE THREAD

**Issue by rragoomundun** [jacekkopecky/living-meta-analysis#96]
After the user chooses to log out he's meta-analyses are still accessible when putting their link into the browser top bar.

Also, notice that when a user is on his profile page and choose to log out he stays on this page. This page is also still accessible by putting its address in the browser top bar.

To make theses information unavailable the only solution is to clear cookies.

**Comment by jacekkopecky** [comment]
@Raphael-R-R in LiMA, we don't have any private stuff at the moment - everything is read-accessible to everybody. This is in the spirit of open research data.

**Comment by jacekkopecky** [comment]
also, clearing cookies only removes the invite code
